### ISSUE TITLE
Sort and Tabix index VCFs

### ISSUE THREAD

**Issue by James-S-Santangelo** [ness-lab/mrt#17]
We'll likely want the VCFs to be sorted and Tabix indexed for downstream analyses.

**Comment by aays** [comment]
If it helps at all, `prep_file()` in [this script](https://github.com/aays/2019-mt-locus/blob/master/analysis/ld-windowed/zns_calc_tabix.py) has some code for this already, although it uses `subprocess.call` with `shell=True` instead of `subprocess.Popen` (which it really should be using instead)
