### ISSUE TITLE
Remove annotation table dependence in VCF to FASTA script

### ISSUE THREAD

**Issue by aays** [ness-lab/mrt#23]
`slim_vcf2fasta_chrom.py` currently requires the Chlamydomonas annotation table (as well as the `ANT` parser) to generate reference sequence. 

This could be removed by adding a separate script that generates that reference sequence as a FASTA file, after which this script would just read in that FASTA and immediately get to assigning alternate alleles based on variants in the SLiM output.

**Comment by James-S-Santangelo** [comment]
This will be done now since we are moving to the _Drosophila_ genome, which has no similar annotation table.
