### ISSUE TITLE
Some cleanup

### ISSUE THREAD

**Issue by aays** [ness-lab/mrt#24]
- It would be good if all scripts/functions/methods had consistent nomenclature. We ought to stick to underscores since that is probably most widely accepted in the Python world.
- Should have consistent quote usage - make sure all quotes are single quotes just for clarity
    - Use double quotes for function documentation (`"""`)
- Add inline documentation to larger classes/functions (i.e. `ANT`, `slim_vcf2fasta_chrom`) 
    - Use [PEP 257](https://www.python.org/dev/peps/pep-0257/) for docstrings

**Comment by James-S-Santangelo** [comment]
In addition to the above, the following files and directories can be removed from the repo and ignored:
- [.Rhistory](https://github.com/ness-lab/mrt/blob/master/.Rhistory)
- [\_\_pychache\_\_](https://github.com/ness-lab/mrt/tree/master/scripts/python/__pycache__)
- [*errfile and *outfile](https://github.com/ness-lab/mrt/tree/master/scripts/batch)
