### ISSUE TITLE
Switch to using Drosophila

### ISSUE THREAD

**Issue by aays** [ness-lab/mrt#30]
Post-lab meeting - swap out using a segment of the _Chlamydomonas_ genome for a region from _D. melanogaster_, and use mutation matrix from Chan et al 2012. See #16 for original issue.

**Comment by aays** [comment]
Working on this now. Ver 6.32 appears to be the latest version of the _D. melanogaster_ genome. I'm going to be downloading `fasta/dmel-all-aligned-r6.32.fasta.gz` as well as the full `gff` dir (since I'm not sure what the differences between the different gffs are) onto hpcnode1. 

Link's at ftp://ftp.flybase.net/genomes/Drosophila_melanogaster/dmel_r6.32_FB2020_01/

(GitHub markdown doesn't treat ftp links like links)

Edit: the correct fasta was `dmel-all-chromosome-r6.32.fasta.gz`

**Comment by James-S-Santangelo** [comment]
Sweet. Why onto HPCNODE and not CALCULON? Did you want to switch over?

**Comment by aays** [comment]
Just as a test for now! I figured I'd explore and prep the files on hpcnode1 first. I've got a fasta file containing just the autosomes, and am now prepping a filtered GFF with just autosomes as well. Will upload to Calculon once I'm done.

**Comment by aays** [comment]
Just dropping this here for now - [Reference paper for the Dmel genome](https://academic.oup.com/nar/article/43/D1/D690/2437432)

**Comment by aays** [comment]
Reference FASTA (`dmel-reference-r6.32.fasta`) has been uploaded to `mrt/resources` on Calculon. The GFF is a bit of a giant mess that seems to have concatenated predicted features from multiple resources -- that said, I'm realizing we don't necessarily need it, so I'm just leaving it on hpcnode1 for now.

**Comment by aays** [comment]
I've added in the mutation matrix derived from the Raleigh population of _D. melanogaster_ in Chan et al. (the original LDhelmet paper) - it's now at `resources/dmel_RAL_mut_mat.txt`:

```
0.47  0.10  0.23  0.19
0.27  0.00  0.14  0.59
0.59  0.14  0.00  0.27
0.20  0.23  0.10  0.47
```

They also provide a mutation matrix from a Rwandan population, but there are minimal (ie at the order of 10^-2) differences between the two, so I think picking either should be fine.

**Comment by aays** [comment]
Going to look into updating the vcf2fasta script today to account for this - should also remove any dependence on `ant` and address #23. I think this issue will be good to close after that.
